---
title: "Research"
---
<hr>
<br>

### Interests
* Bioinformatics
* Predictive Genomics
* Population Genetics
* Data Analytics
* Genetic Epidemiology

<br>

### Projects

1. Desarrollo de un modelo de predicción de la Enfermedad de Alzheimer esporádica y su velocidad de progresión en el departamento del Atlántico. **Principal Investigator**. Financed by Departamento del Atlántico. 2021-2025.
1.	Nuevos ARN no codificantes exosomales y su papel en la patogénesis de la Enfermedad de Alzheimer. **Principal coinvestigator**. Financed by COLCIENCIAS. 2020-2022. <!-- COP$349,977,076.  -->
2.	Variantes genéticas y mutaciones genómicas identificadas por secuenciación de última generación (NGS) en familias Colombianas: en busca de marcadores comunes de tautología autoinmune. **Coinvestigator**. Financed by COLCIENCIAS. 2018-2020. <!-- COP$299,004,175. -->
3.	Identificación de marcadores tempranos de tipo neurológico, neurofisiolófico, neurocognitivo y neuropsiquiátrico en población presintomática con riesgo de enfermedad de Huntington en el Departamento del Atlántico. **Coinvestigator**. Financed by COLCIENCIAS. 2018-2020. <!-- COP$399,995,241. -->
4. Detección de Variantes de Efecto Mayor en Enfermedades Complejas. **Principal Investigator**. Financed by Universidad del Norte. 2017-2018. <!-- COP$20,000,000. -->


<br>

### Achievements
* The identification of variants in the [*LPHN3*](http://www.nature.com/mp/journal/v15/n11/full/mp20106a.html) gene that confer susceptibility to Attention Deficit/Hyperactivity Disorder (ADHD) and [substance use disorder](https://www.nature.com/articles/s41398-019-0396-7), [double the risk](http://www.nature.com/mp/journal/v17/n7/full/mp201159a.html) of developing ADHD, and predict response to stimulant medication and  [severity](http://www.nature.com/tp/journal/v1/n7/full/tp201114a.html) of symptoms.

*  Identified that a common genetic network involving the *LPHN3* gene and the [*NCAM1-DRD2-TTC12*](http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3351604/) gene cluster underlies substance use disorders and disruptive or externalizing disorders.

*  Development of the statistical, computational and analytical framework for the functional analysis of genetic variants in the [*SIX3*](http://hmg.oxfordjournals.org/content/17/24/3919.long)  gene using zebrafish, and the genetic analysis of mutations in the [*NODAL*](http://www.sciencedirect.com/science/article/pii/S1096719209001383) signalling pathway.

*  Development and implementation of a [statistical strategy](http://www.nature.com/mp/journal/v18/n5/full/mp201281a.html) that allowed the identification of genes modifying the age of onset in patients with Alzheimer's disease.  

* Identification of age of onset modifier genes in [familial](https://www.nature.com/articles/mp2015177) and [sporadic](https://onlinelibrary.wiley.com/doi/abs/10.1002/ajmg.b.32493) Alzheimer's disease.

<br>

### University Honors & Awards 

* **Highly Cited Researcher**, Universidad del Norte, Barranquilla, Colombia. March 10, 2022. This recognition is given by the [Vice-Chancellor's Office for Research, Creation and Innovation](https://www.uninorte.edu.co/web/investigacion-desarrollo-e-innovacion) to the 25 highly cited researcher/professors over the last 5 years according to [SCOPUS](https://www.scopus.com/authid/detail.uri?authorId=24336983600) and [Google Scholar](https://scholar.google.com/citations?user=GFxNB78AAAAJ&hl=es&authuser=1).
* **Medalla Orden al Mérito Científico** [Scientific Merit Medal], Universidad del Norte, Barranquilla, Colombia. November 23, 2020. This recognition is given to the professor who has done important work in the field of research and science with national and international recognition, and published his/her scientific activities.
*	**Outstanding Research Award**, Division of Engineering, Universidad del Norte, Barranquilla, Colombia. January 15, 2019. This award recognizes the outstanding publishing record of up to five Professors/Researchers of the Division of Engineering during the previous academic year. 
*	**Visitor Researcher**, Genomics and Predictive Medicine Group, John Curtin School of Medical Research, The Australian National University, Canberra, ACT, Australia. April 11, 2016-2019. 
*	**Eccles Scholarship in Medical Sciences (1279/2010)**, The Australian National University, Canberra, ACT, Australia. This scholarship is awarded to International Students to pursue a full-time program of study for the degree of Doctor of Philosophy of the Australian National University within the John Curtin School of Medical Research. 
*	**Fenner Merit Scholarship (1369/2010)**, The Australian National University, Canberra, ACT, Australia. The scholarship is named in honour of Professor Frank Fenner, and its purpose is to attract students of high calibre to pursue postgraduate research for a PhD degree at the John Curtin School of Medical Research.
*	**ANU Higher Degree Research (HDR) Merit Scholarship**, The Australian National University, Canberra, ACT, Australia. This scholarship covers tuition fees for the standard duration of the PhD program.
*	**Intramural Research Training Award (IRTA)**, Muenke Lab, Medical Genetics Branch, National Human Genome Research Institute, National Institutes of Health, Bethesda, MD, USA. August 2007–August 2012.
<!-- *	**Scholarship** to attend the 4th International Colloquium in Statistics: Statistics in Finances and Industry at the National University of Colombia at Medellín and the Faculty of Financial Engineering, University of Medellín. Medellín, July 27-29, 2006. -->
<!-- *	**Scholarship** to attend the Graduate course “Statistics Genetics and Bioinformatics” by the NHGRI, the Corporación para Investigaciones Biológicas, the University of Antioquia and the National University of Colombia at Medellín. Medellín, Colombia, June 1-9, 2006. -->
<!-- *	**Scholarship** for the Master in Statistics Program, School of Statistics, National University of Colombia at Medellín, 2006. -->
<!-- *	**Scholarship** for the Industrial Engineering Program of the National University of Colombia at Medellín, 2000–2005. -->


<br>


### Press Releases

* Jorge Vélez, la estadística en el estudio del genoma humano, [Universidad del Norte](https://www.uninorte.edu.co/web/grupo-prensa/noticia?articleId=27083229&groupId=13400067), Junio 13, 2022.
* Nuestros profesores investigadores más citados en Scopus y Google Scholar, [Universidad del Norte](https://www.uninorte.edu.co/web/grupo-prensa/noticia?articleId=21513126&groupId=13400067), Marzo 10, 2022.
* En búsqueda del tesoro: La información basada en los datos. Entrevista en [Uninorte FM Estéreo](https://soundcloud.com/uninortefm/en-busqueda-del-tesoro-la-informacion-basada-en-los-datos), Octubre 28, 2021.
* Uninorte ProCaM investiga el genoma para entender el riesgo al cáncer de mamá en el Atlántico, Entrevista en [Uninorte FM Estéreo](https://soundcloud.com/uninortefm/uninorte-procam-investiga-el-genoma-para-entender-el-riesgo-al-cancer-de-mama-en-el-atlantico), Septiembre 9, 2021.
* Nos vinculamos a consorcio internacional que estudia el cáncer de seno en Latinoamérica, [Universidad del Norte](https://www.uninorte.edu.co/web/grupo-prensa/noticia?articleId=16990689&groupId=73923), Septiembre 7, 2021.
* La edad de inicio del Alzheimer: un enigma que abre puertas a la genética, [Revista Intellecta](https://www.uninorte.edu.co/web/intellecta/la-edad-de-inicio-del-alzheimer-un-enigma-que-abre-puertas-a-la-genetica), Edición #5, Octubre 2020.
* Identifican siete subgrupos de pacientes con Chikunguña en Barranquilla, [Universidad del Norte](https://www.uninorte.edu.co/web/grupo-prensa/noticia?articleId=15532955&groupId=73923), Junio 19, 2020.
* Una mirada a la Medicina del Futuro, [Revista Intellecta](https://www.uninorte.edu.co/web/intellecta/una-mirada-a-la-medicina-del-futuro), Edición #4, 2019.
*	La detección del TDAH ya tiene hoja de ruta en Barranquilla, [El Heraldo](https://www.elheraldo.co/ciencia/la-deteccion-del-tdah-ya-tiene-hoja-de-ruta-en-barranquilla-663662), Septiembre 8, 2019.
*	¿Qué relación guardan nuestros genes con el trastorno de déficit de atención e hiperactividad?, [Universidad del Norte](https://www.uninorte.edu.co/web/grupo-prensa/noticia?articleId=14699014&groupId=73923), Agosto 16, 2019.
*	Las variantes genéticas y sus efectos en torno al TDAH, [El Heraldo](https://www.elheraldo.co/ciencia/las-variantes-geneticas-y-sus-efectos-en-torno-al-tdah-596585), Febrero 11, 2019.
*	Predecir si un niño con déficit de atención consumirá drogas sería posible, [El Espectador](https://www.elespectador.com/noticias/salud/predecir-si-un-nino-con-deficit-de-atencion-consumira-drogas-seria-posible-articulo-838880), Febrero 9, 2019.
*	Genética ayudará a tratar pacientes con trastorno de déficit de atención e hiperactividad, [Universidad del Norte](https://www.uninorte.edu.co/web/grupo-prensa/noticia?articleId=14133700&groupId=73923), Febrero 8, 2019.
*	Grupo de investigación identifica marcadores genéticos que retrasan edad de inicio del Alzheimer, [Universidad del Norte](https://www.uninorte.edu.co/web/grupo-prensa/noticia?articleId=13806079&groupId=73923), Septiembre 10, 2018.
*	Referentes mundiales en estudio de Trastorno de Déficit de Atención e Hiperactividad se dieron cita en Uninorte, [Universidad del Norte](https://www.uninorte.edu.co/rss-uninorteco/-/asset_publisher/10Qyg2d9nLC8/content/simposio-de-tdah/73923?inheritRedirect=false), Noviembre 15, 2017.
*	Profesor de Industrial Participa en investigación sobre enfermedades genéticas, [Universidad del Norte](https://www.uninorte.edu.co/web/grupo-prensa/noticia?articleId=12139665&groupId=73923), Mayo 11, 2016.
*	Tras los genes de la enfermedad del olvido, [Revista Intellecta](https://www.uninorte.edu.co/web/intellecta/tras-los-genes-de-la-enfermedad-del-olvido), Edición #2, 2017.
*	Quiere saber si va a sufrir de Alzheimer?,  [Revista Semana](https://www.semana.com/hablan-las-marcas/articulo/quiere-saber-si-va-a-sufrir-de-alzheimer/528653), Junio 15, 2017.
*	Scientists isolate genes that delay Alzheimer’s Disease, [Australian National University Press](http://www.anu.edu.au/news/all-news/scientists-isolate-genes-that-delay-alzheimers-disease), December 2, 2015.
* Gene which delays Alzheimer’s Disease by 17 years discovered by scientists, [The Telegraph](https://www.telegraph.co.uk/news/health/elder/12027693/Gene-which-delays-Alzheimer-Disease-by-17-years-discovered-by-scientists.html), December 1, 2015.
*	Scientists find 'gene that delays Alzheimer’s', [National Health Service](https://www.nhs.uk/news/genetics-and-stem-cells/scientists-find-gene-that-delays-alzheimers/), UK, December 2, 2015.



<center>
<br><br><br>
<hr>
Copyright ® 2022, webpage made with [Rmarkdown](https://rmarkdown.rstudio.com/).
<hr>
</center>
