---
title: "Students"
---
<hr>
<br>

#### Current students

*  Luedis Duarte Barboza. MSc student in Applied Statistics (with [Lorenleyn De La Hoz Alford](https://www.escavador.com/sobre/12240857/lorenleyn-de-la-hoz-alford)). Thesis: *Identificación de Variables Determinantes del Comportamiento Mecánico de Espumas de Poliuretano de Origen Natural*.
*  [Laura Zapata Prada](https://www.linkedin.com/in/laura-zapata-prada?originalSubdomain=co). MSc student in Industrial Engineering (with [Carlos Paternina-Arboleda](https://www.linkedin.com/in/carlos-d-paternina-arboleda-81964b85/?originalSubdomain=co))
*  [Jesús Arévalo Medrano](https://www.linkedin.com/in/jesus-bautista-arevalo-medrano-51666968/?original_referer=https%3A%2F%2Fwww%2Egoogle%2Ecom%2F&originalSubdomain=co). MSc student in Applied Statistics. Thesis: *Determinantes de la Categorización Superior o Muy Superior de las Instituciones Educativas: Caso Distrito de Barranquilla, año 2018*.
*  Lilybeth Martinez Olivares. PhD student in Biomedical Sciences (with [Oscar Vidal Orjuela](https://scienti.minciencias.gov.co/cvlac/visualizador/generarCurriculoCv.do?cod_rh=0000028550))
<br> 
* [Elsy Mejía Segura](https://scholar.google.com/citations?user=Ml5bixkAAAAJ&hl=es). PhD in Psychology with Orientation in Neurosciences (with [Pedro Puentes Rozo](http://scienti.colciencias.gov.co:8081/cvlac/visualizador/generarCurriculoCv.do?cod_rh=0000147133)). Universidad de Flores, Buenos Aires, Argentina.
*  [Carlos M. Ferreira](https://co.linkedin.com/in/carlos-martin-ferreira-vanegas-409003140). PhD student in Industrial Engineering (with [Guisselle García Llinás](https://scienti.colciencias.gov.co/cvlac/visualizador/generarCurriculoCv.do?cod_rh=0000738387))
<!-- *  [Daniela Cassandro De La Hoz](https://co.linkedin.com/in/daniela-cassandro-de-la-hoz-490b82b1). MSc student in Industrial Engineering (with [Carlos Paternina-Arboleda](https://www.linkedin.com/in/carlos-d-paternina-arboleda-81964b85/?originalSubdomain=co)) -->
<!-- *  [Leonella Torreglosa Portillo](https://co.linkedin.com/in/leonella-torreglosa-aa7b44193). MSc student in Industrial Engineering (with [Carlos Paternina-Arboleda](https://scholar.google.com.co/citations?hl=en&user=gqEqfLUAAAAJ)) -->

#### Past students
* [Martha L. Cervantes](https://scienti.colciencias.gov.co/cvlac/visualizador/generarCurriculoCv.do?cod_rh=0000743534). PhD in Biomedical Sciences (with [Pedro Puentes Rozo](http://scienti.colciencias.gov.co:8081/cvlac/visualizador/generarCurriculoCv.do?cod_rh=0000147133)). Thesis: *Variantes Genéticas Asociadas al Trastorno de Déficit de Atención e Hiperactividad en una Comunidad del Caribe Colombiano.* May 2022.  **Magna Cum Laude** [distinction](https://www.uninorte.edu.co/web/grupo-prensa/noticia?articleId=24826754&groupId=13400067).
*  [José Luis López-Prado](https://scienti.colciencias.gov.co/cvlac/visualizador/generarCurriculoCv.do?cod_rh=0001486987). PhD in Industrial Engineering (with [Guisselle García Llinás](https://scienti.colciencias.gov.co/cvlac/visualizador/generarCurriculoCv.do?cod_rh=0000738387)). Thesis: *Modeling of the Rural Distribution System with Applications to Micogrids to Evaluate Reliability.* March 2022.
*  [Luiggi Samper Orozco](https://co.linkedin.com/in/luiggisamper). MSc in [Epidemiology](https://www.uninorte.edu.co/web/maestria-en-epidemiologia). Thesis: _Desarrollo de un Modelo de Genómica Predictiva basado en Machine Learning para la Estimación de la Edad de Inicio de la Enfermedad de Alzheimer: Implicaciones para el Caribe Colombiano_.  September 2021. **Cum Laude** distinction.
*  Elkin Rafael Torres Rivera, MSc in [Applied Statistics](https://www.uninorte.edu.co/web/maestria-en-estadistica-aplicada). Thesis: _Variabilidad Cognitiva en Pacientes con Esquizofrenia_. June 2021. 
*  [Carmen Quintero Arteaga](https://www.linkedin.com/in/carmen-cecilia-quintero-arteaga-8a9972146/), MSc in [Industrial Engineering](https://www.uninorte.edu.co/web/maestria-en-ingenieria-industrial) (with [Rita Peña-baena Niebles](https://scienti.minciencias.gov.co/cvlac/visualizador/generarCurriculoCv.do?cod_rh=0000060496)). Thesis: _Diseño Estadístico de una Carta de Control $\bar{x}$ Sintética Totalmente Adaptativa para Procesos Autocorrelacionados_. March 2021.



<center>
<br><br><br>
<hr>
Copyright ® 2022, webpage made with [Rmarkdown](https://rmarkdown.rstudio.com/).
<hr>
</center>
