---
title: "Teaching"
---
<br>

### Applied Data Science
This a *new* elective course offered to BSc students from the Engineering, Psychology, Mathematics and Economy undergraduate programs at Universidad del Norte. 

Elements of Data Analytics, Computational Statistics, Dimensionality Reduction Techniques, Predictive Modeling and Data Visualization are covered. Of course, most of the work will be performed in [R](https://www.r-project.org/).

For more information, take a look at [Camilo Álvarez](https://github.com/calvarezr7/Curso_AppliedDataAnalytics)'s notes on the course.

<br>


### Data Analysis in Engineering II
This is a course offered to 6th semester students of the [Industrial Engineering](https://www.uninorte.edu.co/web/ingenieria-industrial) program. We introduce basic and intermediate concepts in

1. Simple and Multiple Linear Regression
2. Advanced Linear Regression Models, which include Nonlinear, Logistic and Poisson Regressions
3. Time Series Analysis, including stationary and nonstationary time series, and forecasting methods such as decomposition, smoothing and ARIMA$(p,d,q)$ models
4. Nonparametric statistics, including the sign and signed-rank tests, as well as the Wilcoxon-Mann-Whitney and Kruskal-Wallis tests

I taught this course every semester since 2016-10 until 2020-30.

<br>

### Design of Experiments 

This course is offered once a year to [MSc](https://www.uninorte.edu.co/web/maestria-en-ingenieria-industrial)/ [PhD](https://www.uninorte.edu.co/web/doctorado-en-ingenieria-industrial) students in Industrial Engineering, and [MSc](https://www.uninorte.edu.co/web/maestria-en-ciencias-basicas-biomedicas)/ [PhD](https://www.uninorte.edu.co/web/doctorado-en-ciencias-biomedicas) students in Biomedical Sciences. We explore the fundamentals of 

1. One- and two-fixed factors experimental designs
2. Blocking
3. Designs with one- and two-random factors
4. $2^k$ and $3^k$ designs
5. Response surface methodology

This course has been offered during the 2017-30, 2018-30, 2019-30 and 2020-30 semesters.

<br>


### Introduction to Bioinformatics
This is an introductory course for  [MSc](https://www.uninorte.edu.co/web/maestria-en-ciencias-basicas-biomedicas)/ [PhD](https://www.uninorte.edu.co/web/doctorado-en-ciencias-biomedicas) students of the Biomedical Sciences program. It is offered once a year and covers the following topics:

1. Genome organization
2. Generation of *omics* data
3. Sequencing techniques. 
4. [vcf](https://www.ebi.ac.uk/training/online/course/human-genetic-variation-i-introduction-2019/variant-identification-and-analysis-0#targetText=VCF%20is%20the%20standard%20file%20format%20for%20storing%20variation%20data.&targetText=VCF%20is%20a%20preferred%20format,are%20tab%20delimited%20text%20files.), [BAM](https://genome.sph.umich.edu/wiki/BAM) and [SAM](https://en.wikipedia.org/wiki/SAM_(file_format)) formats
5. Genome and protein databases and how to query them
6. Functional prediction of biological sequences

This course has been offered during the 2017-30, 2018-30 and 2020-10 semesters.

<br>

### Population Genetics
This course is offered once a year to  [MSc](https://www.uninorte.edu.co/web/maestria-en-ciencias-basicas-biomedicas)/ [PhD](https://www.uninorte.edu.co/web/doctorado-en-ciencias-biomedicas)  students in Biomedical Sciences. We discuss

1. General concepts of genetics, including allele frequencies at the population level, the Hardy-Weinberg principle and its implications
2. Principles of Genetic Epidemiology, including inheritance models, pleiotropy, variable expressivity and modifier genes
3. Segregation, linkage and association analysis, genetic differentiation and genetic diversity in humans

This course has been offered during the 2017-10, 2018-10, 2019-10 and 2020-10  semesters.

<br>

### Biostatistics for Biomedical Sciences
This course, first offered during the 2019-30 semester, is oriented to  [MSc](https://www.uninorte.edu.co/web/maestria-en-ciencias-basicas-biomedicas)/ [PhD](https://www.uninorte.edu.co/web/doctorado-en-ciencias-biomedicas)  students in Biomedical Sciences. 

We discuss 

1. Exploratory Data Analysis;
2. Hypothesis testing;
3. Analysis of two-way contingency tables;
3. Simple and multiple linear regression models; and
4. Logistic Regression.


<br>


### Advanced Statistics 
This course is part of the [MSc in Applied Statistics program](https://www.uninorte.edu.co/web/maestria-en-estadistica-aplicada) at Universidad del Norte. First offered under my supervision during the 2020-10 semester, is offered every year. 

We discuss elements of Exploratory Data Analysis, Predictive Modeling and Clustering, as well as their implementation and automation in  [R](https://www.r-project.org/) via [`Rmarkdown`](https://rmarkdown.rstudio.com/).


<center>
<br><br><br>
<hr>
Copyright ® 2021, webpage made with [Rmarkdown](https://rmarkdown.rstudio.com/).
<hr>
</center>
